// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwlAemrMiR9JvI66MfINyYeXl7tU86cM',
    appId: '1:444145783078:web:64b1174e3a8bcc9ad331e7',
    messagingSenderId: '444145783078',
    projectId: 'gkltdd-fc459',
    authDomain: 'gkltdd-fc459.firebaseapp.com',
    databaseURL: 'https://gkltdd-fc459-default-rtdb.firebaseio.com',
    storageBucket: 'gkltdd-fc459.appspot.com',
    measurementId: 'G-YRMB4PP5VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1Bd5MJjAsS_744eeqcfARFsOeAOFswY',
    appId: '1:444145783078:android:b2f7a51f7e9d851dd331e7',
    messagingSenderId: '444145783078',
    projectId: 'gkltdd-fc459',
    databaseURL: 'https://gkltdd-fc459-default-rtdb.firebaseio.com',
    storageBucket: 'gkltdd-fc459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUrSdchEgTrclh_uNrq6IHmNBHGTx8BI',
    appId: '1:444145783078:ios:bda1521ae6fc6f38d331e7',
    messagingSenderId: '444145783078',
    projectId: 'gkltdd-fc459',
    databaseURL: 'https://gkltdd-fc459-default-rtdb.firebaseio.com',
    storageBucket: 'gkltdd-fc459.appspot.com',
    iosBundleId: 'com.example.gkLtdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUrSdchEgTrclh_uNrq6IHmNBHGTx8BI',
    appId: '1:444145783078:ios:bda1521ae6fc6f38d331e7',
    messagingSenderId: '444145783078',
    projectId: 'gkltdd-fc459',
    databaseURL: 'https://gkltdd-fc459-default-rtdb.firebaseio.com',
    storageBucket: 'gkltdd-fc459.appspot.com',
    iosBundleId: 'com.example.gkLtdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwlAemrMiR9JvI66MfINyYeXl7tU86cM',
    appId: '1:444145783078:web:d28ffa4bb4c87248d331e7',
    messagingSenderId: '444145783078',
    projectId: 'gkltdd-fc459',
    authDomain: 'gkltdd-fc459.firebaseapp.com',
    databaseURL: 'https://gkltdd-fc459-default-rtdb.firebaseio.com',
    storageBucket: 'gkltdd-fc459.appspot.com',
    measurementId: 'G-NN3GF4PPVM',
  );
}
